services:
  web:
    container_name: web_cnab
    image: httpd:2.4.55-alpine
    ports:
      - 8080:80
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html
    depends_on:
      - flask
  flask:
    container_name: flask-app
    build: .
    ports:
      - 5000:5000
    environment:
      - POSTGRES_USER=rodrigo
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cnab
      - HOST=db
      - PORT=5432
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: cnab_db
    image: postgres:14
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=rodrigo
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cnab
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rodrigo -d cnab"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
